import 'bootstrap/dist/css/bootstrap.css';
import "./global.css"
  import { ToastContainer } from 'react-toastify';
  import 'react-toastify/dist/ReactToastify.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning>{children}
              <ToastContainer />
     </body>
      
    </html>
  )
}

//import anyname from "./page"      default import only onetime form one file
 
//import {admin ,user} from "./page"  //  const import         many const import from one file
//export const admin = admin     //-----------------------------
//export const user = user      //

//export{admin , user} from "./page" // combine import export like line 18 to 20



//4 ways toh style 

// inline css  style={{}}
// internal css  const style = {}   style= {style}
// global.css
// module.css  